/**
 * MicroConvert - Markdown to PDF Converter Module
 * Implements Converter interface using marked.js, DOMPurify, highlight.js, and html2pdf.js
 */

import type { Converter, ConversionContext, ConversionResult, ValidationResult } from './types';

// Declare global window properties provided by CDN scripts
declare global {
  interface Window {
    marked?: {
      parse: (src: string, options?: any) => string;
      setOptions?: (options: any) => void;
    };
    DOMPurify?: {
      sanitize: (dirty: string, options?: any) => string;
    };
    hljs?: {
      highlightElement: (element: HTMLElement) => void;
    };
    html2pdf?: () => any;
  }
}

export const mdToPdfConverter: Converter = {
  id: 'md-to-pdf',
  name: 'Markdown to PDF',
  description: 'Convert CommonMark and GitHub Flavored Markdown into print-ready PDF documents',
  inputLabel: 'Markdown (.md)',
  outputLabel: 'PDF Document (.pdf)',
  acceptExtensions: ['.md', '.markdown'],
  acceptMimeTypes: ['text/markdown', 'text/x-markdown', 'text/plain'],
  outputExtension: '.pdf',
  outputMimeType: 'application/pdf',
  maxFileSize: 5 * 1024 * 1024, // 5 Megabytes threshold

  sampleFilename: 'MicroConvert-QuickStart.md',
  sampleContent: `# MicroConvert: Professional Document Export

Welcome to **MicroConvert**, the zero-knowledge, 100% client-side document converter. Everything you view and convert runs entirely within your browser memory.

---

## 1. Key Features & Privacy Guarantees

> "Privacy is not an afterthought — client-side conversion means your proprietary data, legal agreements, and personal notes never touch a third-party server."

* **100% Client-Side:** Powered by standard Web APIs (\`FileReader\`, \`Blob\`, \`html2pdf.js\`).
* **Zero Tracking:** No telemetry, analytics, tracking pixels, or remote database storage.
* **Full CommonMark & GFM Support:** Headings, tables, checklists, blockquotes, and code blocks.
* **Smart Page Breaks:** Automatically prevents awkward page breaks inside code blocks and tables.

---

## 2. GitHub Flavored Markdown (GFM) Syntax

### Task Lists & Organization
- [x] Configure client-side marked.js and DOMPurify pipeline
- [x] Implement robust page-break prevention for print output
- [ ] Explore future extensible converter modules

### Feature Comparison Matrix

| Capability | MicroConvert (Client-Side) | Cloud Converters | Legacy Desktop Tools |
| :--- | :---: | :---: | :---: |
| **Data Privacy** | 100% Local / Safe | Transmitted to Server | Local |
| **Installation** | Zero (Runs in Browser) | Zero | Heavy Install |
| **Offline Ready** | Yes (Service Worker) | No | Yes |
| **Speed** | Instant | Network Dependent | Fast |

---

## 3. Code Block Syntax Highlighting

Here is an example demonstrating the modular converter registry pattern:

\`\`\`javascript
// Register a converter module with a unified contract
converterRegistry.register({
  id: 'md-to-pdf',
  name: 'Markdown to PDF',
  acceptExtensions: ['.md', '.markdown'],
  outputExtension: '.pdf',
  convert: async ({ previewEl, filename }) => {
    const worker = window.html2pdf().from(previewEl);
    return await worker.save(filename);
  }
});
\`\`\`

And Python syntax highlighting:

\`\`\`python
def convert_document(filepath: str) -> str:
    """Process document purely in client memory."""
    print(f"Converting {filepath} with zero remote requests.")
    return "document.pdf"
\`\`\`

---

## 4. Typography & Blockquote Hierarchies

### Heading Level 3
#### Heading Level 4
##### Heading Level 5 (Capitalized Label)

You can use *italic emphasis*, **bold weight**, ~~strikethrough text~~, or \`inline monospace code\`.

---

*Generated by MicroConvert • Ready for PDF Export*
`,

  /**
   * Validate file and content according to edge case requirements
   */
  validate(file: File | null, content: string): ValidationResult {
    // 1. Check file extension if a file object is present
    if (file) {
      const fileNameLower = file.name.toLowerCase();
      const hasValidExt = this.acceptExtensions.some((ext) => fileNameLower.endsWith(ext));

      if (!hasValidExt) {
        return {
          valid: false,
          error: `Invalid file format: "${file.name}". MicroConvert expects a Markdown file (${this.acceptExtensions.join(', ')}).`
        };
      }

      // 2. Large file check (>5MB)
      if (file.size > this.maxFileSize) {
        const sizeMb = (file.size / (1024 * 1024)).toFixed(1);
        return {
          valid: true,
          warning: `Large document detected (${sizeMb} MB). Rendering and PDF generation may take a few extra moments.`
        };
      }
    }

    // 3. Check for empty content
    if (!content || content.trim().length === 0) {
      return {
        valid: false,
        error: 'The document is currently empty. Please drop a Markdown file or enter text to preview.'
      };
    }

    return { valid: true };
  },

  /**
   * Parse Markdown to sanitized HTML and render with syntax highlighting
   */
  async parseAndRender(content: string, previewEl: HTMLElement): Promise<void> {
    if (!content || content.trim().length === 0) {
      previewEl.innerHTML = `
        <div class="preview-empty-state">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
            <polyline points="14 2 14 8 20 8"></polyline>
            <line x1="16" y1="13" x2="8" y2="13"></line>
            <line x1="16" y1="17" x2="8" y2="17"></line>
            <polyline points="10 9 9 9 8 9"></polyline>
          </svg>
          <h3>Document Preview</h3>
          <p>Drop a <code>.md</code> file above, or type markdown on the left to see the live print-ready preview.</p>
        </div>
      `;
      return;
    }

    try {
      // 0. Normalize whitespace: strip BOM, normalize line endings, remove trailing whitespace
      const normalized = content
        .replace(/^\uFEFF/, '')           // Strip BOM
        .replace(/\r\n/g, '\n')           // Normalize CRLF to LF
        .replace(/\r/g, '\n')             // Normalize lone CR to LF
        .replace(/[\t ]+$/gm, '')          // Remove trailing whitespace per line
        .replace(/\u00A0/g, ' ');          // Replace non-breaking spaces with regular spaces

      // 1. Parse with marked.js
      let rawHtml = '';
      if (window.marked && typeof window.marked.parse === 'function') {
        rawHtml = window.marked.parse(normalized, {
          gfm: true,
          breaks: true
        });
      } else {
        // Fallback simple preformatted text if marked is not yet available
        rawHtml = `<pre>${escapeHtml(normalized)}</pre>`;
      }

      // 2. Sanitize with DOMPurify
      let cleanHtml = rawHtml;
      if (window.DOMPurify && typeof window.DOMPurify.sanitize === 'function') {
        cleanHtml = window.DOMPurify.sanitize(rawHtml, {
          ADD_ATTR: ['target', 'rel']
        });
      }

      // 3. Render into container
      previewEl.innerHTML = cleanHtml;

      // 4. Highlight code blocks with highlight.js
      if (window.hljs && typeof window.hljs.highlightElement === 'function') {
        const codeBlocks = previewEl.querySelectorAll<HTMLElement>('pre code');
        codeBlocks.forEach((block) => {
          try {
            window.hljs?.highlightElement(block);
          } catch (e) {
            console.warn('[MicroConvert] Code highlight error:', e);
          }
        });
      }
    } catch (err: any) {
      console.error('[MicroConvert] Markdown render error:', err);
      throw new Error(`Markdown Parsing Error: ${err?.message || 'Unknown error'}`);
    }
  },

  /**
   * Convert the rendered preview to PDF via html2pdf.js
   */
  async convert(
    context: ConversionContext,
    onProgress?: (percent: number, message: string) => void
  ): Promise<ConversionResult> {
    const { filename, previewEl, options } = context;

    if (!window.html2pdf) {
      throw new Error('PDF generator engine (html2pdf.js) is not loaded. Please verify your connection or refresh.');
    }

    onProgress?.(15, 'Preparing document layout...');

    // Determine target PDF filename
    let pdfFilename = filename || 'document.pdf';
    if (!pdfFilename.toLowerCase().endsWith('.pdf')) {
      // Strip old extension and append .pdf
      const lastDot = pdfFilename.lastIndexOf('.');
      if (lastDot > 0) {
        pdfFilename = pdfFilename.substring(0, lastDot);
      }
      pdfFilename = `${pdfFilename}.pdf`;
    }

    const paperFormat = options?.paperFormat || 'a4';
    const orientation = options?.orientation || 'portrait';
    
    // Margins in mm: [top, left, bottom, right]
    let marginConfig = [14, 14, 14, 14];
    if (options?.margin === 'compact') {
      marginConfig = [10, 10, 10, 10];
    } else if (options?.margin === 'spacious') {
      marginConfig = [18, 18, 18, 18];
    }

    onProgress?.(35, 'Rasterizing high-resolution pages...');

    // html2pdf configuration with pagebreak rules
    const html2pdfOptions = {
      margin: marginConfig,
      filename: pdfFilename,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: {
        scale: 2, // High resolution rendering
        useCORS: true,
        letterRendering: true,
        logging: false
      },
      jsPDF: {
        unit: 'mm',
        format: paperFormat,
        orientation: orientation
      },
      pagebreak: {
        mode: ['avoid-all', 'css', 'legacy'],
        avoid: ['table', 'tr', 'pre', 'blockquote', 'h1', 'h2', 'h3', 'h4', 'figure']
      }
    };

    onProgress?.(60, 'Assembling PDF vector document...');

    try {
      // Clone preview element to ensure clean styling without viewport scroll restrictions
      const clone = previewEl.cloneNode(true) as HTMLElement;
      clone.style.maxWidth = '800px';
      clone.style.margin = '0 auto';
      clone.style.boxShadow = 'none';
      clone.style.border = 'none';
      clone.style.color = '#1e293b';
      clone.style.background = '#ffffff';

      // Temporary offscreen render container
      const offscreen = document.createElement('div');
      offscreen.style.position = 'fixed';
      offscreen.style.left = '-9999px';
      offscreen.style.top = '0';
      offscreen.style.width = '800px';
      offscreen.style.background = '#ffffff';
      offscreen.appendChild(clone);
      document.body.appendChild(offscreen);

      try {
        const worker = window.html2pdf().set(html2pdfOptions).from(clone);
        
        onProgress?.(85, 'Finalizing download blob...');
        const blob: Blob = await worker.output('blob');

        // Trigger user file download
        await worker.save();

        onProgress?.(100, 'PDF Download Complete!');

        return {
          blob,
          filename: pdfFilename
        };
      } finally {
        // Clean up temporary DOM element
        if (offscreen.parentNode) {
          offscreen.parentNode.removeChild(offscreen);
        }
      }
    } catch (err: any) {
      console.error('[MicroConvert] PDF conversion failed:', err);
      throw new Error(`PDF generation failed: ${err?.message || 'Check console for details'}`);
    }
  }
};

/**
 * Basic HTML escaping helper
 */
function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
